---


- hosts: all
  become: yes
  tasks:
  - name: Update and upgrade apt packages
    apt:
      upgrade: 'yes'
      update_cache: yes
      autoclean: yes
      autoremove: yes
      cache_valid_time: 86400 
  
  - name: Print all available facts
    ansible.builtin.debug:
      var: ansible_facts
