---


- hosts: all
  become: yes
  tasks:
  - name: Update and upgrade apt packages
    apt:
      upgrade: 'full'
      update_cache: yes
      autoclean: yes
      autoremove: yes
      cache_valid_time: 86400 
 
   - name: Update and upgrade apt packages
     apt:
       upgrade: 'dist'
       autoclean: yes
       autoremove: yes 
       
       
  - name: Print all available facts
    ansible.builtin.debug:
      var: ansible_facts
