- hosts: all
  become: yes
  tasks:
  - name: deny everything and enable UFW
    community.general.ufw:
      state: enabled
      policy: deny
  - name: Allow all access to tcp port 3389
    community.general.ufw:
      rule: allow
      port: '3389'
      proto: tcp
  - name: Allow all access to tcp port 22
    community.general.ufw:
      rule: allow
      port: '22'
      proto: tcp
  - name: Allow all access to tcp port 443
    community.general.ufw:
      rule: allow
      port: '443'
      proto: tcp
  - name: Allow all access to tcp port 80
    community.general.ufw:
      rule: allow
      port: '80'
      proto: tcp
  - name: Allow all access to tcp port 81
    community.general.ufw:
      rule: allow
      port: '81'
      proto: tcp 
  - name: Allow all access to tcp port 443
    community.general.ufw:
      rule: allow
      port: '443'
      proto: tcp
  - name: Allow all access to tcp port 4443
    community.general.ufw:
      rule: allow
      port: '4443'
      proto: tcp 
  - name: Allow all access to tcp port 8088
    community.general.ufw:
      rule: allow
      port: '8088'
      proto: tcp 
